language: ruby

script:
  - bundle exec jekyll build
  - bundle exec rake test

branches:
  only:
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false
cache: bundler

notifications:
  email:
    recipients:
      - argos83@gmail.com
    on_success: change
    on_failure: always

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages