# ----
# Site

title: Balance by Celeste
url: "https://somaticbalance.com.au"
baseurl: ""
google_analytics_key: UA-126654417-1
google_verification: _OPZ1XDKeZd_sGEquv49trtNSd9YNLtugRWaLbTvAiY
google_maps_javascript_api_key: AIzaSyDzB8G0Ol_wvkWDR6VBjKMSk38kgFi_CYc
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Balance by Celeste
social:
  name: Balance by Celeste
  links:
    - https://www.facebook.com/balancebyceleste/
    - https://www.linkedin.com/in/celestecarrillo/
    - https://www.instagram.com/balancebyceleste/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  practitioners:
    output: true
    _icon: account_circle
  modalities:
    output: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
      type: "practitioners"
    values:
      _options:
        image_path:
          width: 440
          height: 440
          uploads_dir: "/images/people"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: "/images/post_uploads"
        content:
          width: 1500
          height: 2000
          uploads_dir: "/images/post_uploads"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover


_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
