# Site settings
title: Somatic Balance
description: Rolfing & Yogestalt. Holistic bodywork & body-centered mindfulness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png

# Hero
hero: 
  hero_img: hero.jpg
  hero_title: Somatic Balance
  hero_description: Get back to being your best self

# Contact form
api_token: # Enter API token here

# Contact info
contact:
  phone: xxx xxx xxx
  emergency: xxx xxx xxx
  email: hello@somaticbalance.com
  address: 33 Foster st, Surry Hills - NSW - Australia

intro:
  - Our bodies hold the stories of who we are but more often than not, we find ourselves struggling to even understand what’s really going on within us. We’re physically stressed and emotionally exhausted.
  - It’s time for that to change.

# Opening hours
opening_hours:
  - weekday: Monday – Tuesday
    time: 11:00 – 18:00
  - weekday: Thursday - Friday
    time: 11:00 – 18:00

# Testimonials
testimonials:
  testimonials_img: parallax.jpg

# Map
map:
  api_key: AIzaSyDzB8G0Ol_wvkWDR6VBjKMSk38kgFi_CYc
  zoom: 16
  lat: -33.880361
  lng: 151.2052403
  address: 33 Foster st, Surry Hills - NSW - Australia
  address_details: 33 Foster st, Surry Hills

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2018 Somatic Balance - All rights reserved

# Build settings
markdown: kramdown

exclude: [
  package.json,
  Gruntfile.js,
  node_modules,
  .sass-cache,
  Gemfile,
  Gemfile.lock,
  .gitignore
]

# Theme Settings
analytics: 
google_verification: _OPZ1XDKeZd_sGEquv49trtNSd9YNLtugRWaLbTvAiY
