# Site settings
title: Somatic Balance
description: Rolfing & Yogestalt. Holistic bodywork & body-centered mindfulness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png


promo:
  enabled: false
  close_cookie_timeout: 1800
  closable: true
  img: '/img/mind-body-spirit.jpg'

# Contact info
contact:
  phone: '+61 402 144 408'
  email: hello@somaticbalance.com.au
  address: Surry Hills - NSW - Australia

# Map
map:
  api_key: AIzaSyDzB8G0Ol_wvkWDR6VBjKMSk38kgFi_CYc
  zoom: 16
  lat: -33.880361
  lng: 151.2052403
  address: 33 Foster st, Surry Hills - NSW - Australia
  address_details: 33 Foster st, Surry Hills

bookings_enabled: false

# Social settings
#facebook: http://facebook.com
#twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: © 2018 Somatic Balance - All rights reserved

# Build settings
markdown: kramdown

exclude: [
  package.json,
  Gruntfile.js,
  node_modules,
  .sass-cache,
  Gemfile,
  Gemfile.lock,
  .gitignore
]

# Theme Settings
analytics: UA-126654417-1
google_verification: _OPZ1XDKeZd_sGEquv49trtNSd9YNLtugRWaLbTvAiY
