# ----
# Site

title: Balance by Celeste
url: "https://somaticbalance.com.au"
baseurl: ""
google_analytics_key: UA-126654417-1
google_verification: _OPZ1XDKeZd_sGEquv49trtNSd9YNLtugRWaLbTvAiY
google_maps_javascript_api_key: AIzaSyDzB8G0Ol_wvkWDR6VBjKMSk38kgFi_CYc
disqus_shortname:

contact:
  email: hello@somaticbalance.com.au

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Balance by Celeste
social:
  name: Balance by Celeste
  links:
    - https://www.facebook.com/balancebyceleste/
    - https://www.linkedin.com/in/celestecarrillo/
    - https://www.instagram.com/balancebyceleste/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor
  - Rakefile
  - makefile

collections:
  practitioners:
    output: true
    _icon: account_circle
  modalities:
    output: true
  courses:
    output: true

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  permalink: '/:num/'
  title: ":title"

jekyll-archives:
  enabled: ['tags']

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"


_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
